name: dh_segment
channels:
  - defaults
dependencies:
  - imageio=2.5.0
  - numpy=1.16.2
  - pandas=0.24.2
  - pillow=5.4.1
  - python=3.6
  - scikit-image=0.14.2
  - scikit-learn=0.20.3
  - scipy=1.2.1
  - setuptools=40.8.0
  - shapely=1.6.4
  - tensorflow-gpu==1.13.1
  - tqdm=4.31.1
  - requests=2.21.0
  - pip:
    - better-exceptions==0.2.1
    - opencv-python==4.0.1.23
    - sacred==0.7.4
    - sphinx
    - sphinx-autodoc-typehints
    - sphinx-rtd-theme
    - sphinxcontrib-bibtex
